### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dllu** [nerfstudio-project/gsplat#58] opened 2023-10-18 15:08 UTC
Should probably add an apache license similar to the rest of the nerfstudio project.

For reference, the official gaussian splatting implementation has a [restrictive license that makes it hard to use commercially](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/main/LICENSE.md).

**Comment by rosejn** [comment] 2023-10-19 18:57
It was Apache licensed until this PR: https://github.com/nerfstudio-project/gsplat/pull/52

But there isn't any explanation...

**Comment by JohanVer** [comment] 2023-10-25 09:37
Thanks for the great work! 
Is there any update on the licence? @liruilong940607

**Comment by machenmusik** [comment] 2023-10-25 18:27
Looks like this merged commit https://github.com/nerfstudio-project/gsplat/tree/f6b07c8cda3530f0a9206b0a0a29215eb158c27f was intended to add Apache 2.0 LICENSE, but didn't

**Comment by vye16** [comment] 2023-10-25 18:42
Hi all, we intend to make the license Apache. Please contact
***@***.*** for more details if needed.

**Closed** 2024-01-26 00:54 UTC
