### ISSUE TITLE
Does gsplat support saving the trained data to a splat file?

### ISSUE THREAD

**Issue by abrahamezzeddine** [nerfstudio-project/gsplat#418] opened 2024-09-23 12:09 UTC
Hello,

I am wondering if gsplat support the ability to save the checkpoint to a splat file which can be viewed in other applications? I cannot find any documentation on how to save this as a splat/ply file. Thanks!

**Comment by liruilong940607** [comment] 2024-09-25 21:05
duplicate of #234

**Closed by liruilong940607** 2024-09-25 21:05 UTC
